#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

# presel_feedback              window_gap
# presel_feedback_color
# click_to_focus               pointer_action3              pointer_motion_interval
# focus_follows_pointer        pointer_follows_focus        swallow_first_click
# pointer_action1              pointer_follows_monitor
# pointer_action2              pointer_modifier
# automatic_scheme             ignore_ewmh_fullscreen       remove_disabled_monitors
# center_pseudo_tiled          ignore_ewmh_struts           remove_unplugged_monitors
# directional_focus_tightness  initial_polarity             
# external_rules_command       mapping_events_count         split_ratio
# honor_size_hints             merge_overlapping_monitors   status_prefix
# ignore_ewmh_focus            removal_adjustment
bspc config window_gap 10


# borders
bspc config border_width 3
bspc config focused_border_color '#FF8900'
bspc config active_border_color '#000099'
bspc config normal_border_color '#002200'

# padding
# right_padding left_padding top_padding bottom_padding

# monocle
bspc config bottom_monocle_padding 3
bspc config right_monocle_padding 3
bspc config left_monocle_padding 3
bspc config top_monocle_padding 3
bspc config gapless_monocle true
bspc config borderless_monocle true
#bspc config single_monocle true

bspc config split_ratio          0.52

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Yad state=floating

