#!/usr/bin/env sh
# depends: herbstluftwm
set -eu

. PANEL_DATA

# file pipe
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
herbstclient --idle > "$PANEL_FIFO" &

## Tags
tag_gen(){
    num="${2#[#:.!+-%]}"
    printf "%s%s %s %s" "%{A:herbstclient use ${num}:}" "${1}" "${num}" "%{B-F-A}"
}
tags_gen(){
    for t in $(herbstclient tag_status)
    do
        case "${t%[1-5]*}"
            in
            :) tag_gen "%{B${TAG_BG_BUSY}}%{F${TAG_FG_BUSY}}" "$t";; # tag not empty
            \#) tag_gen "%{B${TAG_BG_CURRENT}}%{F${TAG_FG_CURRENT}}" "$t" ;; # tag focused on monitor
            .) tag_gen "%{B${TAG_BG_EMPTY}}%{F${TAG_FG_EMPTY}}" "$t"   ;; # tag empty
            #!) tag_gen ${urgent} $t;; # urgent window there
            #+) tag_gen '' $t;; # multi-monitor
            #-) printf "DP-3" # tag_gen "" "$t";; # multi-monitor
            #%) tag_gen '' $t;; # multi-monitor
            *) tag_gen "" "${t#?}"           ;;
        esac
    done
}
# window title
window_title(){
    printf "%.48s" "$(herbstclient get_attr clients.focus.title 2> /dev/null ||  echo 'O_o')"
}

button1(){
    printf "%s" "%{B${BUTTON1_BG}}%{F${BUTTON1_FG}}%{A:widget_session &:} BUTTON %{B-F-A}"
}
button2(){
    printf "%s" "%{B${BUTTON1_BG}}%{F${BUTTON1_FG}}%{A:alacritty -e 'pulsemixer' &:} VOL %{B-F-A}"
}

window_ops(){
    printf "%s %b %s" "%{B#003500}%{A:herbstclient close && herbstclient remove:}" "\Uf2d0 \Uf2d1 \Uf656" "%{B-A}"
}

while read -r line;do
    tags=''
    title=''
    case $line
        in
        INIT*)
           tags="$(tags_gen)"
           title="$(window_title)"
            ;;
        tag_changed*)
           tags="$(tags_gen)"
           title="$(window_title)"
            ;;
        focus_changed*)
           tags="$(tags_gen)"
           title="$(window_title)"
           ;;
        *) tags="$(tags_gen)"
           title="$(window_title)"
           ;;
    esac
    printf "%s\n" "%{l}${tags} | ${title} %{r}$(button1) $(button2) $(window_ops)"
done < "$PANEL_FIFO" | lemonbar -p \
    -n "$PANEL_NAME" \
    -g "${WIDTH}x${HEIGHT}+0+0" \
    -B "${COLOR_BG}" \
    -F "${COLOR_FG}" \
    -U "#00ff40" \
    -o 1 -u 0 \
    -f "${FONT_PANGO}" | sh &

herbstclient emit_hook INIT
