#!/usr/bin/env sh
set -eu

# so called WM_NAME for xkill
PANEL_1="bottom_panel"
PANEL_2="top_panel"

if xdo id -a $PANEL_1 1> /dev/null;then
    xdo kill "$(xdo id -a $PANEL_1)"
fi
if xdo id -a $PANEL_2 1> /dev/null;then
    xdo kill "$(xdo id -a $PANEL_2)"
fi

panel_bottom "$PANEL_1"
panel_top "$PANEL_2"
# system tray
stalonetray -c ~/.config/stalonetray/stalonetrayrc 2> /dev/null &

sleep 1
# make them covered when fullscreen
# xdo is a filter based, results crop themselves..
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n1)" "$(xdo id -a $PANEL_1)"
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n1)" "$(xdo id -a $PANEL_2)"
