#!/usr/bin/env sh
set -eu

# so called WM_NAME for xkill
PANEL_1="bottom_panel"
PANEL_2="top_panel"

if xdo id -a $PANEL_1 1> /dev/null;then
    xdo kill "$(xdo id -a $PANEL_1)"
fi
if xdo id -a $PANEL_2 1> /dev/null;then
    xdo kill "$(xdo id -a $PANEL_2)"
fi


panel_bottom "$PANEL_1"
panel_top "$PANEL_2"

# make them covered when fullscreen
xdo above -t "$(xdo id -N Bspwm | sort | head -n1)" "$(xdo id -a $PANEL_1)"
xdo above -t "$(xdo id -N Bspwm | sort | head -n1)" "$(xdo id -a $PANEL_2)"

