#!/usr/bin/env sh
# depends: herbstluftwm
set -eu

. PANEL_DATA

# file pipe
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
herbstclient --idle > "$PANEL_FIFO" &

# color-set background foreground
select="%{B#01f2d1}%{F#041a1e}"
notempty="%{B#007a68}%{F#7fffff}"
empty="%{B#020202}%{F#007a68}"
#urgent=""

## Tags
tag_gen(){
    num="${2#[#:.!+-%]}"
    printf "%s%s %s %s" "%{A:herbstclient use ${num}:}" "${1}" "${num}" "%{B-F-A}"
}
tags_gen(){
    for t in $(herbstclient tag_status)
    do
        case "${t%[1-5]*}"
            in
            :) tag_gen "${notempty}" "$t";; # tag not empty
            \#) tag_gen "${select}" "$t" ;; # tag focused on monitor
            .) tag_gen "${empty}" "$t"   ;; # tag empty
            #!) tag_gen ${urgent} $t;; # urgent window there
            #+) tag_gen '' $t;; # multi-monitor
            #-) printf "DP-3" # tag_gen "" "$t";; # multi-monitor
            #%) tag_gen '' $t;; # multi-monitor
            *) tag_gen "" "${t#?}"           ;;
        esac
    done
}
# window title
window_title(){
    printf "%.32s" "$(herbstclient get_attr clients.focus.title 2> /dev/null ||  echo 'O_o')"
}

window_ops(){
    printf "%s %b %s" "%{B#04f000}%{A:widget_session:}" "\Uf2d0 \Uf2d1 \Uf656" "%{B-A}"
}

while read -r line;do
    tags=''
    title=''
    wops=$(window_ops)
    case $line
        in
        INIT*)
           tags="$(tags_gen)"
           title="$(window_title)"
            ;;
        tag_changed*)
           tags="$(tags_gen)"
           title="$(window_title)"
            ;;
        focus_changed*)
           tags="$(tags_gen)"
           title="$(window_title)"
           ;;
        *) tags="$(tags_gen)"
           title="$(window_title)"
           ;;
    esac
    printf "%s\n" "%{l}${tags} | ${title} %{r}${wops}"
done < "$PANEL_FIFO" | lemonbar -p \
    -n "$PANEL_NAME" \
    -g "${WIDTH}x${HEIGHT}+0+0" \
    -B "${COLOR_BG}" \
    -F "${COLOR_FG}" \
    -U "#00ff40" \
    -o 1 -u 0 \
    -f "SauceCodePro Nerd Font Mono:style=Semibold,Regular:size=16" | sh &

herbstclient emit_hook INIT
