#!/usr/bin/env sh

# popup remimder
# seq 1 3 | dzen2 -p -w '100' -h '15' -fg '#000000' -bg '#FFFFFF' -l '2' -m -ta 'l' -sa 'c'

 # (
# echo "IM TITLE" # Fist line goes to title
# # The following lines go to slave window
# echo "ASHBDJAHSDA "
# echo "KAJSBDKBASKD"
# echo "ASMDLKAMSLD"
# echo "ASKMDLKMDSLAS"
# echo "LKASMDLAKSMD"
 # )
 (cat ~/Downloads/README.dzen ) | dzen2 -p -x "500" -y "500" -w "500" -l "40" -sa 'l' -ta 'c'\
    -title-name 'popup_sysinfo' -e 'onstart=uncollapse;button1=exit;button3=exit'

 # "onstart=uncollapse" ensures that slave window is visible from start.
