#!/usr/bin/env sh
# depends: curl unzip

set -eu
# unpacking some sexy font from nerdfont

            #\
            # \
           #   \         mmmm   mmmm           "      "
          #     \       #"   " #"   "  mmm   mmm    mmm
          #mmmmmm\_     "#mmm  "#mmm  #"  "    #      #
         #         \        "#     "# #        #      #
        #           \   "mmm#" "mmm#" "#mm"  mm#mm  mm#m
       #             \
# ⠄⠄⠸⣿⣿⢣⢶⣟⣿⣖⣿⣷⣻⣮⡿⣽⣿⣻⣖⣶⣤⣭⡉⠄⠄⠄⠄⠄
# ⠄⠄⠄⢹⠣⣛⣣⣭⣭⣭⣁⡛⠻⢽⣿⣿⣿⣿⢻⣿⣿⣿⣽⡧⡄⠄⠄⠄
# ⠄⠄⠄⠄⣼⣿⣿⣿⣿⣿⣿⣿⣿⣶⣌⡛⢿⣽⢘⣿⣷⣿⡻⠏⣛⣀⠄⠄
# ⠄⠄⠄⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⠙⡅⣿⠚⣡⣴⣿⣿⣿⡆⠄
# ⠄⠄⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠄⣱⣾⣿⣿⣿⣿⣿⣿⠄   ~  -
# ⠄⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢸⣿⣿⣿⣿⣿⣿⣿⣿⠄  (O o )
# ⠄⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠣⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄    0
# ⠄⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠑⣿⣮⣝⣛⠿⠿⣿⣿⣿⣿⠄
# ⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⠄⠄⠄⠄⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠄  c==\O
# ⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠄⠄⠄⠄⢹⣿⣿⣿⣿⣿⣿⣿⣿⠁⠄      |
# ⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠄⠄⠄⠄⠄⠸⣿⣿⣿⣿⣿⡿⢟⣣⣀       B


target="${HOME}/.local/share/fonts"
mkdir -p "$target"

# add them here
sauce="SourceCodePro.zip"
monoki="Mononoki.zip"

# the nerd font repo
baseurl="https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/"

cd /tmp 2> /dev/null &&
for font in ${sauce}; do
	echo "Downloading ${font} ..."
	curl -L -O "${baseurl}${font}"
	unzip -tq "${font}" && unzip "${font}" -d "${target}"
done || echo "Cannot reach /tmp directory"
