#!/usr/bin/env sh

set -eu

. DATA_MONITORS
WIDGETW=200
WIDGETH=26
POSX=$(( SCREEN_WIDTH_1 / 2 - WIDGETW ))
POSY=$(( SCREEN_HEIGHT_1 / 2 - WIDGETH ))

case $1 in
    '--up')
        pactl set-sink-volume @DEFAULT_SINK@ +5%
        play "$XDG_DATA_HOME/sounds/volume_up.oga"
        ;;
    '--down') 
        pactl set-sink-volume @DEFAULT_SINK@ -5%
        play "$XDG_DATA_HOME/sounds/volume_up.oga"
        ;;
    '--mute') pactl set-sink-mute @DEFAULT_SINK@ toggle
        exit 0
        ;;
    *) exit 1
esac


# utility sox
curr="$(pactl get-sink-volume @DEFAULT_SINK@ | grep -o '..%' | head -n1)"

