#!/usr/bin/env sh
# depends: sox
set -eu
IFS=$(printf ' \n\t')

RATIO=5

case $1 in
    '--up')
        pactl set-sink-volume @DEFAULT_SINK@ +$RATIO%
        play "$XDG_DATA_HOME/sounds/volume_up.oga" 2> /dev/null
        ;;
    '--down') 
        pactl set-sink-volume @DEFAULT_SINK@ -$RATIO%
        play "$XDG_DATA_HOME/sounds/volume_up.oga" 2> /dev/null
        ;;
    '--mute') pactl set-sink-mute @DEFAULT_SINK@ toggle
        exit 0
        ;;
    *) exit 1
esac


curr="$(pactl get-sink-volume @DEFAULT_SINK@ | grep -o '..%' | head -n1)"
echo $curr
