#!/usr/bin/env sh

set -eu

action=$(yad --list \
    --title="Session" \
    --window-icon="/usr/share/icons/artix/logo-gray.svg" \
    --width=300 \
    --height=400 \
    --text="Session" \
    --text-align="center" \
    --column="" \
    --separator="" \
    --no-headers \
    --center \
    --css="$HOME/.config/gtk-3.0/yad.css" \
    "Suspend")
# ret=$?

# [ $ret -eq 1 ] && exit 0
#
# if [ $ret -eq 2 ]; then
#     gdmflexiserver --startnew &
#     exit 0
# fi
#
case $action in
    Suspend*) loginctl suspend;;
    *) exit 0
esac
