#!/usr/bin/env sh

herbstclient emit_hook reload
# helpers
hc(){ herbstclient "$@"; }
hcs(){ herbstclient attr settings."$1" "$2"; }
hct(){ herbstclient attr theme."$1" "$2"; }

## reset all
hc keyunbind --all
hc mouseunbind --all
hc unrule -F
hc attr theme.reset 1

############
# Keyboard #
############

#Mod=Mod1  # alt
Mod=Mod4   # winkey
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn st -e zsh
hc keybind $Mod-p spawn dmenu_run
# focus frame
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
# focus in cycle
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
# move frame
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
# resizing frames
resizestep=0.01
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep
# add/del frames
hc keybind $Mod-Alt-h split left
hc keybind $Mod-Alt-j split top
hc keybind $Mod-Alt-k split bottom
hc keybind $Mod-Alt-l split right
hc keybind $Mod-Alt-Left split left
hc keybind $Mod-Alt-Down split bottom
hc keybind $Mod-Alt-Up split top
hc keybind $Mod-Alt-Right split right

hc keybind $Mod-w remove
# frame explode into subframes
hc keybind $Mod-b split explode

############
# Key tags #
############

tagTOkey() {
    hc keybind "$Mod-$1" use "$2"
    hc keybind "$Mod-Shift-$1" move "$2"
}
# tag index 0 is `default`, rename to 1 
hc rename default 1
tagTOkey 1 1
# and iter other `number` tag
for t in $(seq 2 5)
do
    hc add "$t"
    tagTOkey "$t" "$t"
done

# cycle tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layout
hc keybind $Mod-Shift-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-s set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-i pseudotile toggle
hc keybind $Mod-space cycle_layout

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace cycle_monitor
hc keybind $Mod-Shift-i jumpto urgent

#############
# Aesthetic #
#############
hcs always_show_frame false
hcs focus_stealing_prevention false
hcs default_frame_layout horizontal
hcs pseudotile_center_threshold 0

hcs frame_border_width 0
hcs frame_gap 0
hcs frame_bg_transparent true

hcs window_border_active_color "#007e00"
hcs window_border_normal_color "#002000"
#window_border_urgent_color = #000000
hcs window_border_width 3
hcs window_gap 5

#hc set smart_window_surroundings false
#hc set smart_frame_surroundings false

# hc set mouse_recenter_gap 0

#########
# Rules #
#########

hc rule focus=on
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class='Yad' floating=on
hc set tree_style '╾│ ├└╼─┐'

############
# monitors #
############

# unlock, just to be sure
hc unlock
#hc set_monitors 1920x1080+0+0
hc detect_monitors

# find the panel
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" "$monitor" &
# done
