#!/usr/bin/env sh

# short helpers
hc(){
    herbstclient "$@"
}
hcs(){
    herbstclient attr settings.$1 $2
}

hc emit_hook reload

# restore last wallpaper or set a random
if [ -x ~/.fehbg ];then
    ~/.fehbg
else
    
fi
xsetroot -bg "#003300"

## reset all
# reload behave strangelly otherwise
hc keyunbind --all
hc mouseunbind --all
hc attr theme.reset 1

##################################################################
# Keyboard
#

# keybindings
#Mod=Mod1  # Use alt
Mod=Mod4   # or super key

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn "${TERMINAL:-st}"
hc keybind $Mod-o spawn rofi -show run
# basic movement
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# moving the window
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-i       split   right   0.5
# frame explode into subframes
hc keybind $Mod-b split explode

# resizing frames
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

##########################################################
# tags, or `workspaces`
tagTOkey() {
    hc keybind "$Mod-$1" use "$2"
    hc keybind "$Mod-Shift-$1" move "$2"
}
# the first tag is name `default` at index 0
# rebind for keyboard at 1
hc rename default 1
tagTOkey 1 1
# adding number tags is simpler
for t in $(seq 2 5)
do
    hc add "$t"
    tagTOkey "$t" "$t"
done

# layouting
hc keybind $Mod-d remove
hc keybind $Mod-Shift-t floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-t set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-space cycle-layout

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-Shift-i jumpto urgent

############################################################
# Aesthetic
# frame
# always_show_frame                  frame_border_normal_color          smart_window_surroundings
# auto_detect_monitors               frame_border_width                 snap_distance
# auto_detect_panels                 frame_gap                          snap_gap
# default_direction_external_only    frame_normal_opacity               swap_monitors_to_get_tag
# default_frame_layout               frame_padding                      tree_style
# focus_crosses_monitor_boundaries   frame_transparent_width            update_dragged_clients
# focus_follows_mouse                gapless_grid                       verbose
# focus_stealing_prevention          hide_covered_windows               window_border_active_color
# frame_active_opacity               monitors_locked                    window_border_inner_color
# frame_bg_active_color              mouse_recenter_gap                 window_border_inner_width
# frame_bg_normal_color              pseudotile_center_threshold        window_border_normal_color
# frame_bg_transparent               raise_on_click                     window_border_urgent_color
# frame_border_active_color          raise_on_focus                     window_border_width
# frame_border_inner_color           raise_on_focus_temporarily         window_gap
# frame_border_inner_width           smart_frame_surroundings           wmname

# spacing
hcs frame_gap 3
hcs window_gap 2

# disable all frame aesthetic
hcs always_show_frame false
hcs frame_bg_transparent true
hcs frame_transparent_width 0

# except border
hcs frame_border_width 2
hcs frame_border_active_color "#00aa55"
hcs frame_border_normal_color "#003333"

# `smart` apparently relates to minimal
hc set smart_window_surroundings false
hc set smart_frame_surroundings false

# hc set mouse_recenter_gap 0

#########################################################################
# Rules

hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
hc set_monitors 1920x1080+0+0
# or simply:
# hc detect_monitors

# # find the panel
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" "$monitor" &
# done

